### ISSUE TITLE
Nagy GUI terv

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#17]
A dokumentáció részeként egy viszonylag részletes látványterv összeállítása.
Legyen rajta egyértelmű, hogy a már rögzített funkciót [usecase-ek] hol találhatóak és hogy működnek.
A kész feladatot a Tervek+Minta branchen belül saját mappába kell feltölteni.

@tobikjanos 
@galkrisztianx 
[ közös feladat ]

**Comment by galkrisztianx** [comment]
Up.

**Comment by TomaOmega** [comment]
- keret kész
- magyarázat írva
- dokumentációba integrálva
- pusholva
