### ISSUE TITLE
Szimulációs fantáziaterv

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#18]
Mindhárman készítünk egy szimulációs fantáziatervet magyarázattal.
Ezek bekerülnek a tervdokumentációba.
Határidő: **2016.03.10 [késő délután]**

@galkrisztianx 
@tobikjanos

**Comment by galkrisztianx** [comment]
Up.

**Comment by galkrisztianx** [comment]
Jani up.
