### ISSUE TITLE
Adatbázisterv 

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#2]
Adatbázisterv grafikus reprezentációjának elkészítése lehetőleg mysql felületen.
Tesztadatok még nem kellenek. A problématér leírása opcionális.
Kész feladat feltöltése a Tervek+Modell branchen belül saját mappába.

**Comment by galkrisztianx** [comment]
Elvállaltam.

**Comment by TomaOmega** [comment]
Hozzád rendeltem, hogy a listából is látszódjon.

**Comment by tobikjanos** [comment]
Átvettem Krisztől.

**Comment by tobikjanos** [comment]
Felrakva. Kész.

**Comment by TomaOmega** [comment]
módosítottuk Krisszel, a frissített verziót Krisz felnyomja a helyére

**Comment by galkrisztianx** [comment]
Frissítve.

**Comment by TomaOmega** [comment]
A Telephely_Tartaly táblában az a tartaly_nev inkább tartaly_id a Tartaly tábla szerint [plusz az is lenne logikus]. Azt majd még kérlek írd át.
A tartály_méret nem egyértelmű hogy mi [szélesség vagy magasság vagy vastagság, kapacitás vagy űrtartalom]. Azt még módosítani kellene szerintem vagy kapacitásra vagy űrtartalomra, az ízlésedre. A kettő logikailag ugyanazt jelenti, az ízlésedre bízom melyik legyen. A sebességet én átírnám áramlási sebességre, az anyag_nevet anyag_típusra a gyártó_e pedig talán jobban hangzik úgy, hogy elosztó-e, de ez utóbbi 3 dolog már csak finomhangolás, nem életbevágóan fontos. Amúgy a felépítés logikus, szép munka!

**Comment by galkrisztianx** [comment]
Javítva.

**Comment by galkrisztianx** [comment]
Javítva.
