### ISSUE TITLE
Használt technológiák

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#20]
A használt technológiák részletes bemutatása.
Képek használata opcionális, de javallott, viszont ne menjenek a tartalom rovására!

**Comment by galkrisztianx** [comment]
Elvállaltam.

**Comment by galkrisztianx** [comment]
Up.

**Comment by TomaOmega** [comment]
Kiegészítendő:

- a legfrissebb **stabil **.NET verziószámával
- git verziókezelő
- github issuetracker

**Comment by TomaOmega** [comment]
A nevek bent vannak a doksiban, a kifejtés még hátravan
