### ISSUE TITLE
Felhasználói esetek

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#3]
Felhasználói esetek és aktorok gyűjtése [ha vannak].
Egyszerű, de a szabványnak megfelelő ábra készítése.
Kész feladat feltöltése a Tervek+Modell branchen belül saját mappába.
EZ A FELADAT ÖSSZEFÜGG A RENDSZERLEÍRÁSOS FELADATTAL! [ #5 ]

**Comment by galkrisztianx** [comment]
Elvállaltam.

**Comment by TomaOmega** [comment]
Minta került a Tervek+Modell branch SABLONOK mappájába.
Az ábra, ami ezt az issuet érinti. A kifejtés egy másik issue-ba tartozik

**Comment by TomaOmega** [comment]
A szöveges leírás bekerült a Tervek+Modell branchen belül a FelhasznaloiEsetek mappába.
A grafikus reprezentációt a SABLONOK mappában levő mintha alapján kell megcsinálni.

- Felsorolás fent
- Aktor balra
- Esetek bekeretezve
- Rendszer neve felül
- Ne legyenek whitespacek az elnevezésekben

**Comment by galkrisztianx** [comment]
Felraktam a béta verziót.

**Comment by TomaOmega** [comment]
Ütemterv megtekintése (--(include)--Keresés az ütemtervben)

Sor rögzítése az ábrán.

**Comment by galkrisztianx** [comment]
Frissítve.
