### ISSUE TITLE
GUI terv DEMO-hoz

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#4]
Egyszerű ábra készítése a két tartályos folyadékteleportálós legelső verzióhoz.
A legelső demo tartalmazni fog grafikus felületet, hogy a megrendelőnek legyen valami fogalma arról, hogy a végleges verzió mire fog majd hasonlítani.
A továbbiakban határozatlan ideig GUI fejlesztés nem történik.

**Comment by galkrisztianx** [comment]
Elvállaltam.

**Comment by galkrisztianx** [comment]
Elfelejtettem feltölteni, ma pótolom.

**Comment by TomaOmega** [comment]
OKS
Majd pls a Tervek+Modell branchen belül legyen valami saját mappában, mondjuk "ElsoDemo".
