### ISSUE TITLE
Rendszerleírás

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#5]
A majd kész rendszer leírása a teljesség igénye nélkül.
Egy közepesen hosszú leírás készítése, ami tartalmazza, hogy a felhasználó hogy fogja tudni használni a programot. Milyen funkciói és lehetőségei lesznek, milyen esetekre fog odafigyelni a rendszer [ütemezés, tartályállapot stb]
Fekete doboz modellen alapuló leírás, a rendszerműködés részleteit, algoritmusokat nem taglalunk benne.
EZ A FELADAT ÖSSZEFÜGG A FELHASZNÁLÓI ESETES FELADATTAL! [ #3 ]

**Comment by tobikjanos** [comment]
Bétát feltöltöttünk.

**Comment by TomaOmega** [comment]
Kiegészítésre és formázásra szorul.
Minta a SABLONOK-ba található vision leírás lehet

**Comment by galkrisztianx** [comment]
Integrálás elkezdődött.
