### ISSUE TITLE
Osztálydiagramm DEMO-hoz

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#6]
Osztálydiagram készítése a folyadékteleportálásos első demoverzióhoz.
A diagram mindenképpen legyen közzétéve szerkeszthető és képformátumban is!
A kész feladatot a Tervek+Modell branchen belül az ElsoDemo mappába kell feltölteni.

**Comment by TomaOmega** [comment]
Elvállaltam. Amint meglesz a GUI terv és megbeszéltük megcsinálom.

**Comment by galkrisztianx** [comment]
Zárom, mert Visual Studio generálja.
