### ISSUE TITLE
Teljes osztálydiagram terv

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#7]
Egy alaposan átgondolt véglegesnek szánt osztálydiagram első verziójának elkészítése.
100%, hogy nem ez lesz a végén, de első körben kell egy fantáziaterv.
A kész terv legyen feltöltve szerkeszthető és képformátumban is!
A kész feladat a Tervek+Minta branchen belül saját mappába kerül.
EZ A FELADAT A DEMO TERV ALAPJÁN KÉSZÜL [ #6  ]

**Comment by galkrisztianx** [comment]
Elkezdve.

**Comment by galkrisztianx** [comment]
Up (félkész).

**Comment by galkrisztianx** [comment]
Up.

**Comment by TomaOmega** [comment]
elvileg kész
