### ISSUE TITLE
Felhasználói esetek kifejtése

### ISSUE THREAD

**Issue by TomaOmega** [TomaOmega/RektLabor#9]
3 a rendszer működése szempontjából lényeges felhasználói eset kifejtése a RUP-nak megfelelő szabványos módon.
Minta van a Tervek+Modell branch SABLONOK mappájában.
A kész feladatot a Tervek+Model branchbe, saját mappába kell feltölteni.
Ez a feladat összefügg a #3 -> Felhasználói esetek issue-val

**Comment by TomaOmega** [comment]
@tobikjanos 
@galkrisztianx 
Ezt majd 3 részre osztjuk és mindenkire jut 1 kifejtés

**Comment by TomaOmega** [comment]
**A három kiválasztott felhasználói eset:**

- Disztribúciós tartály hozzáadása
- Előzetes ütemterv összeállítása
- Előzetes ütemterv elfogadása

**Comment by TomaOmega** [comment]
Első kettő kész, a harmadik még hátravan.

**Comment by TomaOmega** [comment]
**Plusz kifejtendő eset:**

- Előzetes ütemterv analizálása

**Comment by galkrisztianx** [comment]
Up.

**Comment by galkrisztianx** [comment]
Frissítve.
